# Impostazioni DB
spring.datasource.url=jdbc:h2:mem:cartdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Opzionale: permette di vedere la console H2 nel browser
spring.h2.console.enabled=true

# Forza l'uso dell'identity sulle colonne invece delle sequenze
spring.jpa.hibernate.use-new-id-generator-mappings=false
# Assicurati che il dialetto sia specifico per H2
spring.jpa.show-sql:true

# Assicura che Hibernate crei le tabelle prima che Spring provi a popolarle
spring.jpa.defer-datasource-initialization=true

# Specifica che vogliamo caricare i dati (utile se si usa data.sql)
spring.sql.init.mode=always

# Proprietà custom per generare gli utenti...
app.features.db-init.enabled=true

logging.level.root=INFO

app.features.db-init.enabled=true

# Percorso personalizzato per l'interfaccia grafica di Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Ordina gli endpoint in ordine alfabetico (anziché per ordine di apparizione nel codice)
springdoc.swagger-ui.operations-sorter=alpha

# Percorso per il file JSON grezzo della specifica OpenAPI v3
springdoc.api-docs.path=/v3/api-docs

# Opzionale: Abilita il filtraggio degli endpoint nella UI
springdoc.swagger-ui.filter=true